/* Generated By:JavaCC: Do not edit this line. HarpoParserTokenManager.java */
package parser;
import frontEnd.Builder ;
import frontEnd.AST.* ;
import frontEnd.Builder.* ;

/** Token Manager. */
public class HarpoParserTokenManager implements HarpoParserConstants
{
   int commentNestingDepth  ;

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0, long active1)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0xfc7ffc0000000000L) != 0L || (active1 & 0xfe7L) != 0L)
         {
            jjmatchedKind = 76;
            return 26;
         }
         if ((active0 & 0x20000000L) != 0L)
            return 22;
         if ((active0 & 0x30000000000L) != 0L || (active1 & 0x18L) != 0L)
         {
            jjmatchedKind = 76;
            return 11;
         }
         if ((active0 & 0x4000000L) != 0L)
            return 60;
         if ((active0 & 0x1000000L) != 0L)
            return 0;
         if ((active0 & 0x200000000L) != 0L)
            return 53;
         if ((active0 & 0x8000000000L) != 0L)
            return 44;
         if ((active0 & 0x80000000000000L) != 0L)
         {
            jjmatchedKind = 76;
            return 65;
         }
         if ((active0 & 0x300000000000000L) != 0L)
         {
            jjmatchedKind = 76;
            return 5;
         }
         return -1;
      case 1:
         if ((active0 & 0x343a0000000000L) != 0L || (active1 & 0x18L) != 0L)
            return 26;
         if ((active0 & 0xffcbc50000000000L) != 0L || (active1 & 0xfe7L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 76;
               jjmatchedPos = 1;
            }
            return 26;
         }
         return -1;
      case 2:
         if ((active0 & 0x3c2400000000000L) != 0L || (active1 & 0x40L) != 0L)
            return 26;
         if ((active0 & 0xfc29950000000000L) != 0L || (active1 & 0xfbfL) != 0L)
         {
            jjmatchedKind = 76;
            jjmatchedPos = 2;
            return 26;
         }
         return -1;
      case 3:
         if ((active0 & 0xa800800000000000L) != 0L || (active1 & 0x85L) != 0L)
            return 26;
         if ((active0 & 0x5429150000000000L) != 0L || (active1 & 0xf3aL) != 0L)
         {
            jjmatchedKind = 76;
            jjmatchedPos = 3;
            return 26;
         }
         return -1;
      case 4:
         if ((active0 & 0x140000000000L) != 0L || (active1 & 0xb22L) != 0L)
            return 26;
         if ((active0 & 0x5429010000000000L) != 0L || (active1 & 0x418L) != 0L)
         {
            jjmatchedKind = 76;
            jjmatchedPos = 4;
            return 26;
         }
         return -1;
      case 5:
         if ((active0 & 0x5000010000000000L) != 0L || (active1 & 0x18L) != 0L)
            return 26;
         if ((active0 & 0x429000000000000L) != 0L || (active1 & 0x400L) != 0L)
         {
            jjmatchedKind = 76;
            jjmatchedPos = 5;
            return 26;
         }
         return -1;
      case 6:
         if ((active0 & 0x401000000000000L) != 0L || (active1 & 0x400L) != 0L)
            return 26;
         if ((active0 & 0x28000000000000L) != 0L)
         {
            jjmatchedKind = 76;
            jjmatchedPos = 6;
            return 26;
         }
         return -1;
      case 7:
         if ((active0 & 0x28000000000000L) != 0L)
         {
            jjmatchedKind = 76;
            jjmatchedPos = 7;
            return 26;
         }
         return -1;
      case 8:
         if ((active0 & 0x20000000000000L) != 0L)
            return 26;
         if ((active0 & 0x8000000000000L) != 0L)
         {
            jjmatchedKind = 76;
            jjmatchedPos = 8;
            return 26;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0, long active1)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 40:
         jjmatchedKind = 11;
         return jjMoveStringLiteralDfa1_0(0x4L, 0x0L);
      case 41:
         return jjStopAtPos(0, 12);
      case 42:
         return jjStopAtPos(0, 32);
      case 43:
         return jjStopAtPos(0, 30);
      case 44:
         return jjStopAtPos(0, 35);
      case 45:
         return jjStopAtPos(0, 31);
      case 46:
         return jjStartNfaWithStates_0(0, 39, 44);
      case 47:
         return jjStartNfaWithStates_0(0, 33, 53);
      case 58:
         jjmatchedKind = 17;
         return jjMoveStringLiteralDfa1_0(0x1000000000L, 0x0L);
      case 59:
         return jjStopAtPos(0, 34);
      case 60:
         return jjStartNfaWithStates_0(0, 26, 60);
      case 61:
         return jjStartNfaWithStates_0(0, 24, 0);
      case 62:
         return jjStartNfaWithStates_0(0, 29, 22);
      case 91:
         return jjStopAtPos(0, 13);
      case 93:
         return jjStopAtPos(0, 14);
      case 97:
         return jjMoveStringLiteralDfa1_0(0x30000000000L, 0x18L);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x400L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x1c0000000000L, 0x800L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x600000000000L, 0x0L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x1800000000000L, 0x0L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x2000000000000L, 0x0L);
      case 103:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x220L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x3c000000000000L, 0x0L);
      case 109:
         return jjMoveStringLiteralDfa1_0(0x40000000000000L, 0x0L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x80000000000000L, 0x0L);
      case 111:
         return jjMoveStringLiteralDfa1_0(0x300000000000000L, 0x0L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x1c00000000000000L, 0xc0L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0xe000000000000000L, 0x100L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x7L);
      case 123:
         return jjStopAtPos(0, 15);
      case 124:
         jjmatchedKind = 37;
         return jjMoveStringLiteralDfa1_0(0x4000000000L, 0x0L);
      case 125:
         return jjStopAtPos(0, 16);
      default :
         return jjMoveNfa_0(1, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0, long active1)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1);
      return 1;
   }
   switch(curChar)
   {
      case 42:
         if ((active0 & 0x4L) != 0L)
            return jjStopAtPos(1, 2);
         break;
      case 61:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStopAtPos(1, 36);
         break;
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x100L);
      case 98:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000000000000L, active1, 0L);
      case 99:
         return jjMoveStringLiteralDfa2_0(active0, 0x10000000000L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000000000000L, active1, 0L);
      case 102:
         if ((active0 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 50, 26);
         break;
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x6000000000000000L, active1, 0x23L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x400000000000L, active1, 0x204L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x840000000000L, active1, 0x800L);
      case 109:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000000000000L, active1, 0L);
      case 110:
         if ((active0 & 0x10000000000000L) != 0L)
         {
            jjmatchedKind = 52;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x20000000000000L, active1, 0L);
      case 111:
         if ((active0 & 0x80000000000L) != 0L)
         {
            jjmatchedKind = 43;
            jjmatchedPos = 1;
         }
         else if ((active0 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 45, 26);
         return jjMoveStringLiteralDfa2_0(active0, 0x42100000000000L, active1, 0x480L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0xc00000000000000L, active1, 0x40L);
      case 115:
         if ((active0 & 0x20000000000L) != 0L)
         {
            jjmatchedKind = 41;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x18L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x1200000000000000L, active1, 0L);
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000000000L, active1, 0L);
      case 121:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000000000000000L, active1, 0L);
      case 124:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStopAtPos(1, 38);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(0, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1);
      return 2;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000000L, active1, 0x800L);
      case 98:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000000000000L, active1, 0L);
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000000L, active1, 0L);
      case 100:
         if ((active0 & 0x40000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 54, 26);
         break;
      case 101:
         if ((active1 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(2, 70, 26);
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000000000000L, active1, 0x1L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x400000000000000L, active1, 0x2L);
      case 106:
         if ((active0 & 0x100000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 56, 26);
         break;
      case 107:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x100L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000000000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000000000000L, active1, 0x20L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x8008000000000000L, active1, 0L);
      case 114:
         if ((active0 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 49, 26);
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000000000000L, active1, 0x400L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000000000L, active1, 0x98L);
      case 116:
         if ((active0 & 0x200000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 57, 26);
         return jjMoveStringLiteralDfa3_0(active0, 0x21000000000000L, active1, 0x4L);
      case 118:
         if ((active0 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 46, 26);
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x200L);
      case 119:
         if ((active0 & 0x80000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 55, 26);
         break;
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(1, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, active1);
      return 3;
   }
   switch(curChar)
   {
      case 99:
         if ((active0 & 0x800000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 59, 26);
         break;
      case 101:
         if ((active0 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 47, 26);
         else if ((active0 & 0x8000000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 63, 26);
         return jjMoveStringLiteralDfa4_0(active0, 0x4021010000000000L, active1, 0x308L);
      case 104:
         if ((active1 & 0x4L) != 0L)
            return jjStartNfaWithStates_0(3, 66, 26);
         break;
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x800L);
      case 108:
         return jjMoveStringLiteralDfa4_0(active0, 0x1008000000000000L, active1, 0x2L);
      case 110:
         if ((active0 & 0x2000000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 61, 26);
         else if ((active1 & 0x1L) != 0L)
            return jjStartNfaWithStates_0(3, 64, 26);
         break;
      case 114:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x400L);
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x140000000000L, active1, 0x20L);
      case 116:
         if ((active1 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(3, 71, 26);
         break;
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x10L);
      case 118:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, active1);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(2, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, active1);
      return 4;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x4400000000000000L, active1, 0L);
      case 101:
         if ((active1 & 0x2L) != 0L)
            return jjStartNfaWithStates_0(4, 65, 26);
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000000000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000000000000L, active1, 0L);
      case 109:
         if ((active1 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(4, 75, 26);
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x10L);
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000000000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x400L);
      case 112:
         return jjMoveStringLiteralDfa5_0(active0, 0x10000000000L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x20000000000000L, active1, 0x8L);
      case 115:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 42, 26);
         else if ((active1 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(4, 72, 26);
         else if ((active1 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(4, 73, 26);
         break;
      case 116:
         if ((active0 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 44, 26);
         else if ((active1 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(4, 69, 26);
         break;
      default :
         break;
   }
   return jjStartNfa_0(3, active0, active1);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(3, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, active1);
      return 5;
   }
   switch(curChar)
   {
      case 99:
         if ((active0 & 0x1000000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 60, 26);
         break;
      case 100:
         if ((active0 & 0x4000000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 62, 26);
         return jjMoveStringLiteralDfa6_0(active0, 0x1000000000000L, active1, 0L);
      case 101:
         if ((active1 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(5, 68, 26);
         break;
      case 102:
         return jjMoveStringLiteralDfa6_0(active0, 0x20000000000000L, active1, 0L);
      case 109:
         return jjMoveStringLiteralDfa6_0(active0, 0x8000000000000L, active1, 0L);
      case 116:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 40, 26);
         else if ((active1 & 0x8L) != 0L)
            return jjStartNfaWithStates_0(5, 67, 26);
         return jjMoveStringLiteralDfa6_0(active0, 0x400000000000000L, active1, 0L);
      case 119:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x400L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0, active1);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(4, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, active1);
      return 6;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x20000000000000L, active1, 0L);
      case 101:
         if ((active0 & 0x400000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 58, 26);
         return jjMoveStringLiteralDfa7_0(active0, 0x8000000000000L, active1, 0L);
      case 115:
         if ((active0 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 48, 26);
         else if ((active1 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(6, 74, 26);
         break;
      default :
         break;
   }
   return jjStartNfa_0(5, active0, active1);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(5, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, 0L);
      return 7;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa8_0(active0, 0x20000000000000L);
      case 110:
         return jjMoveStringLiteralDfa8_0(active0, 0x8000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0, 0L);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, 0L);
      return 8;
   }
   switch(curChar)
   {
      case 101:
         if ((active0 & 0x20000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 53, 26);
         break;
      case 116:
         return jjMoveStringLiteralDfa9_0(active0, 0x8000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0, 0L);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0, 0L);
      return 9;
   }
   switch(curChar)
   {
      case 115:
         if ((active0 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 51, 26);
         break;
      default :
         break;
   }
   return jjStartNfa_0(8, active0, 0L);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0x0L, 0x40000L
};
static final long[] jjbitVec1 = {
   0x0L, 0x0L, 0x0L, 0x10000L
};
static final long[] jjbitVec2 = {
   0x0L, 0x0L, 0x0L, 0x100000L
};
static final long[] jjbitVec3 = {
   0x10000000000L, 0x0L, 0x0L, 0x0L
};
static final long[] jjbitVec4 = {
   0x8000000000L, 0x0L, 0x0L, 0x0L
};
static final long[] jjbitVec5 = {
   0x0L, 0x0L, 0x100000000000L, 0x0L
};
static final long[] jjbitVec6 = {
   0x0L, 0x100000000L, 0x0L, 0x0L
};
static final long[] jjbitVec7 = {
   0x0L, 0x1000000000L, 0x0L, 0x0L
};
static final long[] jjbitVec8 = {
   0x0L, 0x2000000000000000L, 0x0L, 0x0L
};
static final long[] jjbitVec9 = {
   0x0L, 0x2000000000L, 0x0L, 0x0L
};
static final long[] jjbitVec10 = {
   0x0L, 0x4000000000000000L, 0x0L, 0x0L
};
static final long[] jjbitVec11 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 87;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 65:
               case 26:
                  if ((0x3ff009000000000L & l) == 0L)
                     break;
                  if (kind > 76)
                     kind = 76;
                  jjCheckNAdd(26);
                  break;
               case 1:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 77)
                        kind = 77;
                     jjCheckNAddStates(0, 7);
                  }
                  else if (curChar == 60)
                     jjAddStates(8, 9);
                  else if (curChar == 47)
                     jjAddStates(10, 11);
                  else if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 44;
                  else if (curChar == 36)
                  {
                     if (kind > 76)
                        kind = 76;
                     jjCheckNAdd(26);
                  }
                  else if (curChar == 62)
                     jjstateSet[jjnewStateCnt++] = 22;
                  else if (curChar == 61)
                     jjstateSet[jjnewStateCnt++] = 0;
                  if (curChar == 49)
                     jjstateSet[jjnewStateCnt++] = 37;
                  else if (curChar == 56)
                     jjstateSet[jjnewStateCnt++] = 33;
                  else if (curChar == 50)
                     jjstateSet[jjnewStateCnt++] = 28;
                  break;
               case 60:
                  if (curChar == 61)
                     jjstateSet[jjnewStateCnt++] = 61;
                  if (curChar == 61)
                  {
                     if (kind > 19)
                        kind = 19;
                  }
                  break;
               case 5:
                  if ((0x3ff009000000000L & l) == 0L)
                     break;
                  if (kind > 76)
                     kind = 76;
                  jjCheckNAdd(26);
                  break;
               case 53:
                  if (curChar != 47)
                     break;
                  if (kind > 1)
                     kind = 1;
                  jjCheckNAddStates(12, 14);
                  break;
               case 11:
                  if ((0x3ff009000000000L & l) == 0L)
                     break;
                  if (kind > 76)
                     kind = 76;
                  jjCheckNAdd(26);
                  break;
               case 0:
                  if (curChar == 62 && kind > 18)
                     kind = 18;
                  break;
               case 7:
                  if (curChar == 47 && kind > 21)
                     kind = 21;
                  break;
               case 15:
                  if (curChar == 61 && kind > 25)
                     kind = 25;
                  break;
               case 19:
                  if (curChar == 60 && kind > 27)
                     kind = 27;
                  break;
               case 23:
                  if (curChar == 62)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 25:
                  if (curChar != 36)
                     break;
                  if (kind > 76)
                     kind = 76;
                  jjCheckNAdd(26);
                  break;
               case 27:
                  if (curChar == 50)
                     jjstateSet[jjnewStateCnt++] = 28;
                  break;
               case 28:
                  if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 29:
                  if ((0x3000000000000L & l) == 0L)
                     break;
                  if (kind > 78)
                     kind = 78;
                  jjCheckNAddTwoStates(30, 31);
                  break;
               case 30:
                  if ((0x3000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(30, 31);
                  break;
               case 31:
                  if ((0x3000000000000L & l) != 0L && kind > 78)
                     kind = 78;
                  break;
               case 32:
                  if (curChar == 56)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 33:
                  if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 34:
                  if ((0xff000000000000L & l) == 0L)
                     break;
                  if (kind > 79)
                     kind = 79;
                  jjCheckNAddTwoStates(35, 36);
                  break;
               case 35:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(35, 36);
                  break;
               case 36:
                  if ((0xff000000000000L & l) != 0L && kind > 79)
                     kind = 79;
                  break;
               case 37:
                  if (curChar == 54)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 38:
                  if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 39:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 80)
                     kind = 80;
                  jjCheckNAddTwoStates(40, 41);
                  break;
               case 40:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(40, 41);
                  break;
               case 41:
                  if ((0x3ff000000000000L & l) != 0L && kind > 80)
                     kind = 80;
                  break;
               case 42:
                  if (curChar == 49)
                     jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 43:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 44:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 82)
                     kind = 82;
                  jjCheckNAddStates(15, 17);
                  break;
               case 45:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(45, 46);
                  break;
               case 46:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 82)
                     kind = 82;
                  jjCheckNAdd(47);
                  break;
               case 48:
                  if ((0x280000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 49;
                  break;
               case 49:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 82)
                     kind = 82;
                  jjCheckNAddTwoStates(50, 51);
                  break;
               case 50:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(50, 51);
                  break;
               case 51:
                  if ((0x3ff000000000000L & l) != 0L && kind > 82)
                     kind = 82;
                  break;
               case 52:
                  if (curChar == 47)
                     jjAddStates(10, 11);
                  break;
               case 54:
                  if ((0xffffffffffffdbffL & l) == 0L)
                     break;
                  if (kind > 1)
                     kind = 1;
                  jjCheckNAddStates(12, 14);
                  break;
               case 55:
                  if ((0x2400L & l) != 0L && kind > 1)
                     kind = 1;
                  break;
               case 56:
                  if (curChar == 10 && kind > 1)
                     kind = 1;
                  break;
               case 57:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 56;
                  break;
               case 59:
                  if (curChar == 60)
                     jjAddStates(8, 9);
                  break;
               case 61:
                  if (curChar == 62 && kind > 20)
                     kind = 20;
                  break;
               case 62:
                  if (curChar == 61)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 68:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 77)
                     kind = 77;
                  jjCheckNAddStates(0, 7);
                  break;
               case 69:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(69, 70);
                  break;
               case 70:
                  if ((0x3ff000000000000L & l) != 0L && kind > 77)
                     kind = 77;
                  break;
               case 71:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(71, 72);
                  break;
               case 72:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(73);
                  break;
               case 73:
                  if (curChar != 46)
                     break;
                  if (kind > 82)
                     kind = 82;
                  jjCheckNAddTwoStates(74, 78);
                  break;
               case 75:
                  if ((0x280000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 76;
                  break;
               case 76:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 82)
                     kind = 82;
                  jjCheckNAddTwoStates(77, 51);
                  break;
               case 77:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(77, 51);
                  break;
               case 78:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 82)
                     kind = 82;
                  jjCheckNAddStates(18, 20);
                  break;
               case 79:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(79, 80);
                  break;
               case 80:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 82)
                     kind = 82;
                  jjCheckNAdd(74);
                  break;
               case 81:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(81, 82);
                  break;
               case 82:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(83);
                  break;
               case 84:
                  if ((0x280000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 85;
                  break;
               case 85:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 82)
                     kind = 82;
                  jjCheckNAddTwoStates(86, 51);
                  break;
               case 86:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(86, 51);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 65:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 76)
                        kind = 76;
                     jjCheckNAdd(26);
                  }
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 66;
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 64;
                  break;
               case 1:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 76)
                        kind = 76;
                     jjCheckNAdd(26);
                  }
                  else if (curChar == 126)
                     jjCheckNAdd(15);
                  else if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 7;
                  if (curChar == 110)
                     jjAddStates(21, 22);
                  else if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 19;
                  else if (curChar == 126)
                  {
                     if (kind > 23)
                        kind = 23;
                  }
                  else if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 11;
                  else if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 5:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 76)
                        kind = 76;
                     jjCheckNAdd(26);
                  }
                  if (curChar == 114)
                  {
                     if (kind > 21)
                        kind = 21;
                  }
                  break;
               case 53:
                  if (curChar == 92 && kind > 22)
                     kind = 22;
                  break;
               case 11:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 76)
                        kind = 76;
                     jjCheckNAdd(26);
                  }
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 6:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 8:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 10:
                  if (curChar == 100 && kind > 22)
                     kind = 22;
                  break;
               case 12:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 14:
                  if (curChar == 126 && kind > 23)
                     kind = 23;
                  break;
               case 16:
                  if (curChar == 126)
                     jjCheckNAdd(15);
                  break;
               case 20:
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 22:
                  if (curChar == 95 && kind > 28)
                     kind = 28;
                  break;
               case 25:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 76)
                     kind = 76;
                  jjCheckNAdd(26);
                  break;
               case 26:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 76)
                     kind = 76;
                  jjCheckNAdd(26);
                  break;
               case 30:
                  if (curChar == 95)
                     jjAddStates(23, 24);
                  break;
               case 35:
                  if (curChar == 95)
                     jjAddStates(25, 26);
                  break;
               case 39:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 80)
                     kind = 80;
                  jjCheckNAddTwoStates(40, 41);
                  break;
               case 40:
                  if ((0x7e8000007eL & l) != 0L)
                     jjCheckNAddTwoStates(40, 41);
                  break;
               case 41:
                  if ((0x7e0000007eL & l) != 0L && kind > 80)
                     kind = 80;
                  break;
               case 45:
                  if (curChar == 95)
                     jjAddStates(27, 28);
                  break;
               case 47:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(29, 30);
                  break;
               case 50:
                  if (curChar == 95)
                     jjCheckNAddTwoStates(50, 51);
                  break;
               case 54:
                  if (kind > 1)
                     kind = 1;
                  jjAddStates(12, 14);
                  break;
               case 63:
                  if (curChar == 110)
                     jjAddStates(21, 22);
                  break;
               case 64:
                  if (curChar == 116 && kind > 23)
                     kind = 23;
                  break;
               case 66:
                  if (curChar == 116)
                     jjCheckNAdd(15);
                  break;
               case 67:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 66;
                  break;
               case 69:
                  if (curChar == 95)
                     jjAddStates(31, 32);
                  break;
               case 71:
                  if (curChar == 95)
                     jjAddStates(33, 34);
                  break;
               case 74:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(35, 36);
                  break;
               case 77:
                  if (curChar == 95)
                     jjCheckNAddTwoStates(77, 51);
                  break;
               case 79:
                  if (curChar == 95)
                     jjAddStates(37, 38);
                  break;
               case 81:
                  if (curChar == 95)
                     jjAddStates(39, 40);
                  break;
               case 83:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(41, 42);
                  break;
               case 86:
                  if (curChar == 95)
                     jjCheckNAddTwoStates(86, 51);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (int)(curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 18)
                        kind = 18;
                  }
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 19)
                        kind = 19;
                  }
                  if (jjCanMove_2(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 20)
                        kind = 20;
                  }
                  if (jjCanMove_3(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 21)
                        kind = 21;
                  }
                  if (jjCanMove_4(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 22)
                        kind = 22;
                  }
                  if (jjCanMove_5(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 23)
                        kind = 23;
                  }
                  if (jjCanMove_6(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 25)
                        kind = 25;
                  }
                  if (jjCanMove_5(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 15;
                  if (jjCanMove_7(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 27)
                        kind = 27;
                  }
                  if (jjCanMove_8(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 28)
                        kind = 28;
                  }
                  break;
               case 2:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2) && kind > 18)
                     kind = 18;
                  break;
               case 3:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2) && kind > 19)
                     kind = 19;
                  break;
               case 4:
                  if (jjCanMove_2(hiByte, i1, i2, l1, l2) && kind > 20)
                     kind = 20;
                  break;
               case 9:
                  if (jjCanMove_3(hiByte, i1, i2, l1, l2) && kind > 21)
                     kind = 21;
                  break;
               case 13:
                  if (jjCanMove_4(hiByte, i1, i2, l1, l2) && kind > 22)
                     kind = 22;
                  break;
               case 14:
                  if (jjCanMove_5(hiByte, i1, i2, l1, l2) && kind > 23)
                     kind = 23;
                  break;
               case 17:
                  if (jjCanMove_6(hiByte, i1, i2, l1, l2) && kind > 25)
                     kind = 25;
                  break;
               case 18:
                  if (jjCanMove_5(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 21:
                  if (jjCanMove_7(hiByte, i1, i2, l1, l2) && kind > 27)
                     kind = 27;
                  break;
               case 24:
                  if (jjCanMove_8(hiByte, i1, i2, l1, l2) && kind > 28)
                     kind = 28;
                  break;
               case 54:
                  if (!jjCanMove_9(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 1)
                     kind = 1;
                  jjAddStates(12, 14);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 87 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
private int jjMoveStringLiteralDfa0_1()
{
   switch(curChar)
   {
      case 40:
         return jjMoveStringLiteralDfa1_1(0x8L);
      case 42:
         return jjMoveStringLiteralDfa1_1(0x20L);
      default :
         return 1;
   }
}
private int jjMoveStringLiteralDfa1_1(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      return 1;
   }
   switch(curChar)
   {
      case 41:
         if ((active0 & 0x20L) != 0L)
            return jjStopAtPos(1, 5);
         break;
      case 42:
         if ((active0 & 0x8L) != 0L)
            return jjStopAtPos(1, 3);
         break;
      default :
         return 2;
   }
   return 2;
}
private int jjMoveStringLiteralDfa0_2()
{
   return 1;
}
static final int[] jjnextStates = {
   69, 70, 71, 72, 73, 81, 82, 83, 60, 62, 53, 58, 54, 55, 57, 45, 
   46, 47, 79, 80, 74, 65, 67, 30, 31, 35, 36, 45, 46, 48, 49, 69, 
   70, 71, 72, 75, 76, 79, 80, 81, 82, 84, 85, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 33:
         return ((jjbitVec0[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_1(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 33:
         return ((jjbitVec1[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_2(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 33:
         return ((jjbitVec2[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_3(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 34:
         return ((jjbitVec3[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_4(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 34:
         return ((jjbitVec4[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_5(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec5[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_6(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 34:
         return ((jjbitVec6[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_7(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 34:
         return ((jjbitVec7[i2] & l2) != 0L);
      case 42:
         return ((jjbitVec8[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_8(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 34:
         return ((jjbitVec9[i2] & l2) != 0L);
      case 42:
         return ((jjbitVec10[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_9(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec11[i2] & l2) != 0L);
      default :
         return false;
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, "\50", "\51", 
"\133", "\135", "\173", "\175", "\72", null, null, null, null, null, null, "\75", null, 
"\74", null, null, "\76", "\53", "\55", "\52", "\57", "\73", "\54", "\72\75", "\174", 
"\174\174", "\56", "\141\143\143\145\160\164", "\141\163", "\143\154\141\163\163", 
"\143\157", "\143\157\156\163\164", "\144\157", "\144\151\166", "\145\154\163\145", 
"\145\170\164\145\156\144\163", "\146\157\162", "\151\146", "\151\155\160\154\145\155\145\156\164\163", 
"\151\156", "\151\156\164\145\162\146\141\143\145", "\155\157\144", "\156\145\167", 
"\157\142\152", "\157\165\164", "\160\162\151\166\141\164\145", "\160\162\157\143", 
"\160\165\142\154\151\143", "\164\150\145\156", "\164\150\162\145\141\144", "\164\171\160\145", 
"\167\150\145\156", "\167\150\151\154\145", "\167\151\164\150", "\141\163\163\145\162\164", 
"\141\163\163\165\155\145", "\147\150\157\163\164", "\160\162\145", "\160\157\163\164", 
"\164\141\153\145\163", "\147\151\166\145\163", "\142\157\162\162\157\167\163", 
"\143\154\141\151\155", null, null, null, null, null, null, null, null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
   "IN_MULTI_LINE_COMMENT",
   "FINISH_MULTI_LINE_COMMENT",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, 1, -1, -1, -1, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0xfffffffffffff801L, 0x15ffffL, 
};
static final long[] jjtoSkip = {
   0x7c2L, 0x0L, 
};
static final long[] jjtoSpecial = {
   0x42L, 0x0L, 
};
static final long[] jjtoMore = {
   0x3cL, 0x0L, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[87];
private final int[] jjstateSet = new int[174];
private final StringBuilder jjimage = new StringBuilder();
private StringBuilder image = jjimage;
private int jjimageLen;
private int lengthOfMatch;
protected char curChar;
/** Constructor. */
public HarpoParserTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public HarpoParserTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 87; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 3 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   if (jjmatchedPos < 0)
   {
      if (image == null)
         curTokenImage = "";
      else
         curTokenImage = image.toString();
      beginLine = endLine = input_stream.getBeginLine();
      beginColumn = endColumn = input_stream.getBeginColumn();
   }
   else
   {
      String im = jjstrLiteralImages[jjmatchedKind];
      curTokenImage = (im == null) ? input_stream.GetImage() : im;
      beginLine = input_stream.getBeginLine();
      beginColumn = input_stream.getBeginColumn();
      endLine = input_stream.getEndLine();
      endColumn = input_stream.getEndColumn();
   }
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      matchedToken.specialToken = specialToken;
      return matchedToken;
   }
   image = jjimage;
   image.setLength(0);
   jjimageLen = 0;

   for (;;)
   {
     switch(curLexState)
     {
       case 0:
         try { input_stream.backup(0);
            while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
               curChar = input_stream.BeginToken();
         }
         catch (java.io.IOException e1) { continue EOFLoop; }
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_0();
         if (jjmatchedPos == 0 && jjmatchedKind > 84)
         {
            jjmatchedKind = 84;
         }
         break;
       case 1:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_1();
         if (jjmatchedPos == 0 && jjmatchedKind > 4)
         {
            jjmatchedKind = 4;
         }
         break;
       case 2:
         jjmatchedKind = 6;
         jjmatchedPos = -1;
         curPos = 0;
         curPos = jjMoveStringLiteralDfa0_2();
         break;
     }
     if (jjmatchedKind != 0x7fffffff)
     {
        if (jjmatchedPos + 1 < curPos)
           input_stream.backup(curPos - jjmatchedPos - 1);
        if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
        {
           matchedToken = jjFillToken();
           matchedToken.specialToken = specialToken;
       if (jjnewLexState[jjmatchedKind] != -1)
         curLexState = jjnewLexState[jjmatchedKind];
           return matchedToken;
        }
        else if ((jjtoSkip[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
        {
           if ((jjtoSpecial[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
           {
              matchedToken = jjFillToken();
              if (specialToken == null)
                 specialToken = matchedToken;
              else
              {
                 matchedToken.specialToken = specialToken;
                 specialToken = (specialToken.next = matchedToken);
              }
              SkipLexicalActions(matchedToken);
           }
           else
              SkipLexicalActions(null);
         if (jjnewLexState[jjmatchedKind] != -1)
           curLexState = jjnewLexState[jjmatchedKind];
           continue EOFLoop;
        }
        MoreLexicalActions();
      if (jjnewLexState[jjmatchedKind] != -1)
        curLexState = jjnewLexState[jjmatchedKind];
        curPos = 0;
        jjmatchedKind = 0x7fffffff;
        try {
           curChar = input_stream.readChar();
           continue;
        }
        catch (java.io.IOException e1) { }
     }
     int error_line = input_stream.getEndLine();
     int error_column = input_stream.getEndColumn();
     String error_after = null;
     boolean EOFSeen = false;
     try { input_stream.readChar(); input_stream.backup(1); }
     catch (java.io.IOException e1) {
        EOFSeen = true;
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
        if (curChar == '\n' || curChar == '\r') {
           error_line++;
           error_column = 0;
        }
        else
           error_column++;
     }
     if (!EOFSeen) {
        input_stream.backup(1);
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
     }
     throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
   }
  }
}

void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void MoreLexicalActions()
{
   jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
   switch(jjmatchedKind)
   {
      case 2 :
         image.append(input_stream.GetSuffix(jjimageLen));
         jjimageLen = 0;
         commentNestingDepth = 1 ;
         break;
      case 3 :
         image.append(input_stream.GetSuffix(jjimageLen));
         jjimageLen = 0;
         ++commentNestingDepth ;
         break;
      case 5 :
         image.append(input_stream.GetSuffix(jjimageLen));
         jjimageLen = 0;
         commentNestingDepth -= 1;
         SwitchTo( commentNestingDepth==0 ? FINISH_MULTI_LINE_COMMENT : IN_MULTI_LINE_COMMENT ) ;
         break;
      default :
         break;
   }
}
private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
